# Generated by Django 4.2.5 on 2024-02-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='test',
        ),
        migrations.AddField(
            model_name='submission',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
