# Generated by Django 4.2.5 on 2024-02-22 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_submission_test_submission_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
