# Generated by Django 4.2.5 on 2024-02-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_submission_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
