# Generated by Django 4.2.5 on 2024-02-22 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_submission_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='type_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
