# Generated by Django 4.2.5 on 2024-02-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_remove_test_duration_remove_test_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.test'),
            preserve_default=False,
        ),
    ]
